#!/usr/bin/env bash
# first commit

sudo apt update
sudo apt updagre
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
