#!/usr/bin/env bash
# comment

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# create an index.html page
touch /etc/nginx/html/index.html

echo "Holberton School" > /etc/nginx/html/index.html

# Create custom 404 error page
echo "<!DOCTYPE html>
<html>
<head>
  <title>404 Not Found</title>
</head>
<body>
  <h1>404 Not Found</h1>
  <p>Ceci n'est pas une page</p>
</body>
</html>" | sudo tee /var/www/html/404.html >/dev/null

# Configure Nginx to use custom 404 error page
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root        /etc/nginx/html;
    index       index.html index.htm;

    root /var/www/html;

    # Error pages
    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}' | sudo tee /etc/nginx/sites-available/default >/dev/null

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
